2014-01-17 13:16:50,069 [WARNING] django.request: Not Found: /p/WikibaseClient/blocked=17&product=MediaWiki extensions&component=WikidataClient
2014-01-18 20:53:59,405 [WARNING] django.request: Not Found: /wikipedia/commons/thumb/f/fd/Chhota_imambara_Lucknow.jpg/320px-Chhota_imambara_Lucknow.jpg
2014-01-18 20:54:02,509 [WARNING] django.request: Not Found: /ajax/libs/jquery/1.7.2/jquery.min.js
2014-01-18 20:54:04,832 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 20:54:04,845 [WARNING] django.request: Not Found: /ajax/libs/lodash.js/0.4.2/lodash.min.js
2014-01-18 20:54:25,443 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 20:54:26,433 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 20:54:26,493 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 20:54:27,352 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 20:54:30,577 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 20:54:30,636 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 20:54:32,572 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 20:54:44,523 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 21:28:35,947 [WARNING] django.request: Not Found: /ajax/libs/jquery/1.7.2/jquery.min.js
2014-01-18 21:28:36,120 [WARNING] django.request: Not Found: /wikipedia/commons/thumb/f/fd/Chhota_imambara_Lucknow.jpg/320px-Chhota_imambara_Lucknow.jpg
2014-01-18 21:28:36,207 [WARNING] django.request: Not Found: /ajax/libs/lodash.js/0.4.2/lodash.min.js
2014-01-18 21:28:36,207 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 21:28:56,156 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 21:28:57,195 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 21:29:20,814 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 21:30:13,855 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 21:30:14,955 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 21:30:16,875 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 22:12:05,692 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 22:12:34,713 [WARNING] django.request: Not Found: /ajax/libs/jquery/1.7.2/jquery.min.js
2014-01-18 22:12:34,833 [WARNING] django.request: Not Found: /ajax/libs/lodash.js/0.4.2/lodash.min.js
2014-01-18 22:12:35,193 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 22:12:46,346 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 22:12:46,348 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 22:12:46,346 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 22:12:47,361 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 22:12:48,163 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 22:12:48,628 [WARNING] django.request: Not Found: /wikipedia/commons/thumb/f/fd/Chhota_imambara_Lucknow.jpg/320px-Chhota_imambara_Lucknow.jpg
2014-01-18 22:12:51,215 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-18 22:12:54,123 [WARNING] django.request: Not Found: /ajax/libs/lodash.js/0.4.2/lodash.min.js
2014-01-18 22:12:54,123 [WARNING] django.request: Not Found: /ajax/libs/jquery/1.7.2/jquery.min.js
2014-01-18 22:12:54,146 [WARNING] django.request: Forbidden (CSRF cookie not set.): /
2014-01-26 09:35:57,129 [ERROR] django.request: Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    if hasattr(response, 'render') and callable(response.render):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    if not self._is_rendered:
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 79, in rendered_content
    """
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 55, in resolve_template
    if isinstance(template, (list, tuple)):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 187, in select_template
    
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 145, in get_template
    """
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 134, in find_template
    """
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 42, in __call__
    def __call__(self, template_name, template_dirs=None):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 48, in load_template
    try:
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    the templates in the list. Returns a string.
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 267, in parse
    # code knows why it terminated
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 214, in do_extends
    parent_name = parser.compile_filter(bits[1])
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 267, in parse
    # code knows why it terminated
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line 1045, in load
    {% load news.photos %}
TemplateSyntaxError: 'i18n' is not a valid tag library: ImportError raised loading django.templatetags.i18n: cannot import name render_value_in_context
2014-01-26 09:36:06,736 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 181, in get_response
    callback, param_dict = resolver.resolve400()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 363, in resolve400
    return self._resolve_special('400')
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 354, in _resolve_special
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/local/django/scrumbugz/urls.py", line 6, in <module>
    admin.autodiscover()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 25, in autodiscover
    mod = import_module(app)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
ImportError: No module named browser_id
2014-01-26 10:21:25,094 [ERROR] django.request: Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    if hasattr(response, 'render') and callable(response.render):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    if not self._is_rendered:
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 79, in rendered_content
    """
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 57, in resolve_template
    elif isinstance(template, six.string_types):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 145, in get_template
    """
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 134, in find_template
    """
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 42, in __call__
    def __call__(self, template_name, template_dirs=None):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 48, in load_template
    try:
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 156, in get_template_from_string
    the templates in the list. Returns a string.
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 267, in parse
    # code knows why it terminated
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 214, in do_extends
    parent_name = parser.compile_filter(bits[1])
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 267, in parse
    # code knows why it terminated
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line 1045, in load
    {% load news.photos %}
TemplateSyntaxError: 'i18n' is not a valid tag library: ImportError raised loading django.templatetags.i18n: cannot import name render_value_in_context
2014-01-26 10:34:57,916 [ERROR] django.request: Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 181, in get_response
    callback, param_dict = resolver.resolve400()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 363, in resolve400
    return self._resolve_special('400')
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 354, in _resolve_special
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/local/django/scrumbugz/urls.py", line 6, in <module>
    admin.autodiscover()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 25, in autodiscover
    mod = import_module(app)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
ImportError: No module named browser_id
2014-01-26 11:30:28,239 [ERROR] django.request: Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 181, in get_response
    callback, param_dict = resolver.resolve400()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 363, in resolve400
    return self._resolve_special('400')
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 354, in _resolve_special
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/local/django/scrumbugz/urls.py", line 12, in <module>
    url(r'^browserid/', include('django_browserid.urls')),
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 26, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/urls.py", line 20, in <module>
    Verify = import_function_from_setting('BROWSERID_VERIFY_CLASS')
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/util.py", line 43, in import_function_from_setting
    mod = import_module(module)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/local/django/scrumbugz/verify.py", line 10
    
   ^
SyntaxError: invalid syntax
2014-01-26 11:45:07,379 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/templates/base.html", line 2, in template
    {% load browserid %}
TemplateSyntaxError: Encountered unknown tag 'load'.
2014-01-26 11:56:55,355 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/templates/base.html", line 28, in template
    {% browserid_css %}
TemplateSyntaxError: Encountered unknown tag 'browserid_css'.
2014-01-26 12:55:19,517 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/templates/base.html", line 2, in template
    {% autoescape true %}
TemplateSyntaxError: Encountered unknown tag 'autoescape'.
2014-01-26 13:06:18,629 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/templates/base.html", line 158, in template
    
TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endautoescape'. The innermost block that needs to be closed is 'autoescape'.
2014-01-26 13:07:58,596 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/templates/base.html", line 2, in template
    {% autoescape true %}
TemplateSyntaxError: Encountered unknown tag 'autoescape'.
2014-01-26 13:23:32,183 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/templates/base.html", line 2, in template
    {% autoescape %}
TemplateSyntaxError: unexpected 'end of statement block'
2014-01-26 13:25:46,820 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/templates/base.html", line 2, in template
    {% autoescape %}
TemplateSyntaxError: unexpected 'end of statement block'
2014-01-26 13:28:30,231 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/templates/base.html", line 14, in template
    {% autoescape %}
TemplateSyntaxError: unexpected 'end of statement block'
2014-01-26 13:36:53,614 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 79, in top-level template code
    {{ browserid_logout(text='Logout') }}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/helpers.py", line 156, in browserid_logout
    reverse('browserid_logout'))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/helpers.py", line 85, in browserid_button
    'attrs': attrs,
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 164, in render_to_string
    return t.render(Context(dictionary))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/templates/browserid/button.html", line 1, in top-level template code
    <a {% for key, value in attrs.items %}{{ key }}="{{ value }}" {% endfor %}>
TypeError: 'builtin_function_or_method' object is not iterable
2014-01-26 13:48:36,485 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 81, in top-level template code
    {{ browserid_login(text='Login', color='dark') }}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/helpers.py", line 131, in browserid_login
    return browserid_button(text, next, link_class, attrs, fallback_href)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/helpers.py", line 85, in browserid_button
    'attrs': attrs,
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 164, in render_to_string
    return t.render(Context(dictionary))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/templates/browserid/button.html", line 1, in top-level template code
    <a {% for key, value in attrs.items %}{{ key }}="{{ value }}" {% endfor %}>
TypeError: 'builtin_function_or_method' object is not iterable
2014-01-26 13:48:38,551 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 81, in top-level template code
    {{ browserid_login(text='Login', color='dark') }}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/helpers.py", line 131, in browserid_login
    return browserid_button(text, next, link_class, attrs, fallback_href)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/helpers.py", line 85, in browserid_button
    'attrs': attrs,
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 164, in render_to_string
    return t.render(Context(dictionary))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/templates/browserid/button.html", line 1, in top-level template code
    <a {% for key, value in attrs.items %}{{ key }}="{{ value }}" {% endfor %}>
TypeError: 'builtin_function_or_method' object is not iterable
2014-01-26 14:09:52,563 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 79, in top-level template code
    {{ browserid_logout(text='Logout') }}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/helpers.py", line 156, in browserid_logout
    reverse('browserid_logout'))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/helpers.py", line 85, in browserid_button
    'attrs': attrs,
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 164, in render_to_string
    return t.render(Context(dictionary))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/templates/browserid/button.html", line 1, in top-level template code
    <a {% for key, value in attrs.items %}{{ key }}="{{ value }}" {% endfor %}>
TypeError: 'builtin_function_or_method' object is not iterable
2014-01-26 14:10:34,429 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 79, in top-level template code
    {{ browserid_logout(text='Logout') }}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/helpers.py", line 156, in browserid_logout
    reverse('browserid_logout'))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/helpers.py", line 85, in browserid_button
    'attrs': attrs,
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 164, in render_to_string
    return t.render(Context(dictionary))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/templates/browserid/button.html", line 1, in top-level template code
    <a {% for key, value in attrs.items %}{{ key }}="{{ value }}" {% endfor %}>
TypeError: 'builtin_function_or_method' object is not iterable
2014-01-26 14:39:41,311 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/templates/base.html", line 2, in template
    {% load browserid %}
TemplateSyntaxError: Encountered unknown tag 'load'.
2014-01-26 14:56:27,893 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 79, in top-level template code
    {{ browserid_logout(text='Logout') }}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/helpers.py", line 156, in browserid_logout
    reverse('browserid_logout'))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/helpers.py", line 85, in browserid_button
    'attrs': attrs,
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 164, in render_to_string
    return t.render(Context(dictionary))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/templates/browserid/button.html", line 1, in top-level template code
    <a {% for key, value in attrs.items %}{{ key }}="{{ value }}" {% endfor %}>
TypeError: 'builtin_function_or_method' object is not iterable
2014-01-26 15:39:41,747 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    if hasattr(response, 'render') and callable(response.render):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    if not self._is_rendered:
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 79, in rendered_content
    """
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 55, in resolve_template
    if isinstance(template, (list, tuple)):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 187, in select_template
    
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 145, in get_template
    """
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 128, in find_template
    return (source, make_origin(display_name, loader, name, dirs))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 95, in find_template_loader
    
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    for character in name:
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loaders/app_directories.py", line 18, in <module>
    if six.PY2:
AttributeError: 'module' object has no attribute 'PY2'
2014-01-26 15:39:54,708 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    if hasattr(response, 'render') and callable(response.render):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    if not self._is_rendered:
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    context = self.resolve_context(self.context_data)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/project.html", line 2, in top-level template code
    {% from "scrum/includes/macros.html" import bug_table with context %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/base_project.html", line 2, in top-level template code
    {% from "scrum/includes/macros.html" import left_nav %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/base.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 48, in top-level template code
    {% if perms.scrum.add_team %}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 376, in getattr
    return obj[attribute]
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/context_processors.py", line 12, in __getitem__
    return self.user.has_perm("%s.%s" % (self.app_label, perm_name))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/functional.py", line 248, in _setup
    self._setup()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 16, in <lambda>
    assert hasattr(request, 'session'), "The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE_CLASSES setting to insert 'django.contrib.sessions.middleware.SessionMiddleware'."
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 8, in get_user
    def get_user(request):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 100, in get_user
    if hasattr(user, 'is_authenticated') and not user.is_authenticated():
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 16, in load_backend
    return import_by_path(path)()
ImproperlyConfigured: Error importing authentication backend django.contrib.auth.backends.ModelBackend: "cannot import name get_user_model"
2014-01-26 15:39:58,037 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    if hasattr(response, 'render') and callable(response.render):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    if not self._is_rendered:
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 79, in rendered_content
    """
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 55, in resolve_template
    if isinstance(template, (list, tuple)):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 187, in select_template
    
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 145, in get_template
    """
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 128, in find_template
    return (source, make_origin(display_name, loader, name, dirs))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 95, in find_template_loader
    
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    for character in name:
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loaders/app_directories.py", line 18, in <module>
    if six.PY2:
AttributeError: 'module' object has no attribute 'PY2'
2014-01-26 15:42:27,320 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    if hasattr(response, 'render') and callable(response.render):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    if not self._is_rendered:
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 79, in rendered_content
    """
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 55, in resolve_template
    if isinstance(template, (list, tuple)):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 187, in select_template
    
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 145, in get_template
    """
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 128, in find_template
    return (source, make_origin(display_name, loader, name, dirs))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 95, in find_template_loader
    
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    for character in name:
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loaders/app_directories.py", line 18, in <module>
    if six.PY2:
AttributeError: 'module' object has no attribute 'PY2'
2014-01-26 15:46:25,369 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 181, in get_response
    callback, param_dict = resolver.resolve400()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 363, in resolve400
    return self._resolve_special('400')
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 354, in _resolve_special
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/local/django/scrumbugz/urls.py", line 12, in <module>
    url(r'^browserid/', include('django_browserid.urls')),
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 26, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/urls.py", line 6, in <module>
    from django.conf.urls.defaults import patterns, url
ImportError: No module named defaults
2014-01-26 15:49:23,470 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 181, in get_response
    callback, param_dict = resolver.resolve400()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 363, in resolve400
    return self._resolve_special('400')
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 354, in _resolve_special
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/local/django/scrumbugz/urls.py", line 12, in <module>
    url(r'^browserid/', include('django_browserid.urls')),
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 26, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django_browserid/urls.py", line 6, in <module>
    from django.conf.urls.defaults import patterns, url
ImportError: No module named defaults
2014-01-26 15:55:20,581 [ERROR] django.request: Internal Server Error: /p/WikibaseClient/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    context = self.resolve_context(self.context_data)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 159, in resolve_context
    return RequestContext(self._request, context, current_app=self._current_app)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/context.py", line 168, in __init__
    for processor in get_standard_processors() + processors:
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/context.py", line 148, in get_standard_processors
    func = import_by_path(path)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/module_loading.py", line 31, in import_by_path
    error_prefix, module_path, class_name))
ImproperlyConfigured: Module "django_browserid.context_processors" does not define a "browserid" attribute/class
2014-01-26 15:55:36,458 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    context = self.resolve_context(self.context_data)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 159, in resolve_context
    return RequestContext(self._request, context, current_app=self._current_app)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/context.py", line 168, in __init__
    for processor in get_standard_processors() + processors:
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/context.py", line 148, in get_standard_processors
    func = import_by_path(path)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/module_loading.py", line 31, in import_by_path
    error_prefix, module_path, class_name))
ImproperlyConfigured: Module "django_browserid.context_processors" does not define a "browserid" attribute/class
2014-01-26 15:59:25,224 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    context = self.resolve_context(self.context_data)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 159, in resolve_context
    return RequestContext(self._request, context, current_app=self._current_app)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/context.py", line 168, in __init__
    for processor in get_standard_processors() + processors:
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/context.py", line 148, in get_standard_processors
    func = import_by_path(path)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/module_loading.py", line 31, in import_by_path
    error_prefix, module_path, class_name))
ImproperlyConfigured: Module "django_browserid.context_processors" does not define a "browserid" attribute/class
2014-01-26 15:59:28,889 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    context = self.resolve_context(self.context_data)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 159, in resolve_context
    return RequestContext(self._request, context, current_app=self._current_app)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/context.py", line 168, in __init__
    for processor in get_standard_processors() + processors:
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/context.py", line 148, in get_standard_processors
    func = import_by_path(path)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/utils/module_loading.py", line 31, in import_by_path
    error_prefix, module_path, class_name))
ImproperlyConfigured: Module "django_browserid.context_processors" does not define a "browserid" attribute/class
2014-01-26 17:41:46,673 [WARNING] django.request: Not Found: /tasks
2014-01-26 17:42:17,009 [WARNING] django.request: Not Found: /ae/
2014-01-26 17:48:49,966 [ERROR] django.request: Internal Server Error: /p/new/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/project_form.html", line 2, in top-level template code
    {% from "bootstrap/forms/macros.html" import field %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/base_project.html", line 2, in top-level template code
    {% from "scrum/includes/macros.html" import left_nav %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/base.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 102, in top-level template code
    {% block content %}{% endblock %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/base.html", line 11, in block "content"
    {% block main_content %}{% endblock %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/project_form.html", line 17, in block "main_content"
    {{ field(f) }}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/bootstrap/templates/bootstrap/forms/macros.html", line 55, in template
    {{ input(field, prepend_content, append_content) }}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/bootstrap/templates/bootstrap/forms/macros.html", line 30, in template
    {{ field|safe }}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/filters.py", line 705, in do_mark_safe
    return Markup(value)
  File "/usr/lib/python2.7/dist-packages/markupsafe/__init__.py", line 71, in __new__
    return unicode.__new__(cls, base)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/forms.py", line 425, in __str__
    return self.as_widget()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/forms.py", line 475, in as_widget
    return widget.render(name, self.value(), attrs=attrs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/floppyforms/widgets.py", line 98, in render
    context_instance=self.context_instance)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 164, in render_to_string
    return t.render(Context(dictionary))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/floppyforms/templates/floppyforms/input.html", line 1, in top-level template code
    <input type="{{ type }}" name="{{ name }}"{% if value %} value="{{ value }}"{% endif %}{% if required %} required{% endif %}{% include "floppyforms/attrs.html" %}{% if datalist %} list="{{ attrs.id }}_list"{% endif %}>{% if datalist %}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/floppyforms/templates/floppyforms/attrs.html", line 1, in top-level template code
    {% for name, value in attrs.items %} {{ name }}{% if value != True %}="{{ value }}"{% endif %}{% endfor %}
TypeError: 'builtin_function_or_method' object is not iterable
2014-01-26 17:48:58,517 [ERROR] django.request: Internal Server Error: /p/new/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/project_form.html", line 2, in top-level template code
    {% from "bootstrap/forms/macros.html" import field %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/base_project.html", line 2, in top-level template code
    {% from "scrum/includes/macros.html" import left_nav %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/base.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 102, in top-level template code
    {% block content %}{% endblock %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/base.html", line 11, in block "content"
    {% block main_content %}{% endblock %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/project_form.html", line 17, in block "main_content"
    {{ field(f) }}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/bootstrap/templates/bootstrap/forms/macros.html", line 55, in template
    {{ input(field, prepend_content, append_content) }}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/bootstrap/templates/bootstrap/forms/macros.html", line 30, in template
    {{ field|safe }}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/filters.py", line 705, in do_mark_safe
    return Markup(value)
  File "/usr/lib/python2.7/dist-packages/markupsafe/__init__.py", line 71, in __new__
    return unicode.__new__(cls, base)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/forms.py", line 425, in __str__
    return self.as_widget()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/forms.py", line 475, in as_widget
    return widget.render(name, self.value(), attrs=attrs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/floppyforms/widgets.py", line 98, in render
    context_instance=self.context_instance)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 164, in render_to_string
    return t.render(Context(dictionary))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/floppyforms/templates/floppyforms/input.html", line 1, in top-level template code
    <input type="{{ type }}" name="{{ name }}"{% if value %} value="{{ value }}"{% endif %}{% if required %} required{% endif %}{% include "floppyforms/attrs.html" %}{% if datalist %} list="{{ attrs.id }}_list"{% endif %}>{% if datalist %}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/floppyforms/templates/floppyforms/attrs.html", line 1, in top-level template code
    {% for name, value in attrs.items %} {{ name }}{% if value != True %}="{{ value }}"{% endif %}{% endfor %}
TypeError: 'builtin_function_or_method' object is not iterable
2014-01-26 17:59:40,137 [ERROR] django.request: Internal Server Error: /p/test/bugs/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/floppyforms/templates/floppyforms/layouts/table.html", line 1, in template
    {% load floppyforms %}{% block formconfig %}{% formconfig row using "floppyforms/rows/tr.html" %}{% endblock %}
TemplateSyntaxError: Encountered unknown tag 'load'.
2014-01-26 18:11:25,722 [ERROR] django.request: Internal Server Error: /p/test/bugs/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/floppyforms/templates/floppyforms/layouts/table.html", line 1, in template
    {% block formconfig %}{% formconfig row using "floppyforms/rows/tr.html" %}{% endblock %}
TemplateSyntaxError: Encountered unknown tag 'formconfig'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2014-01-26 18:22:31,405 [ERROR] django.request: Internal Server Error: /p/test/bugs/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/floppyforms/templates/floppyforms/layouts/table.html", line 1, in template
    {% include form.html %}{% block formconfig %}{% formconfig row using "floppyforms/rows/tr.html" %}{% endblock %}
TemplateSyntaxError: Encountered unknown tag 'formconfig'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2014-01-26 18:23:28,185 [ERROR] django.request: Internal Server Error: /p/test/bugs/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/floppyforms/templates/floppyforms/layouts/table.html", line 1, in template
    {% load floppyforms %}{% block formconfig %}{% formconfig row using "floppyforms/rows/tr.html" %}{% endblock %}
TemplateSyntaxError: Encountered unknown tag 'load'.
2014-01-26 18:25:17,796 [ERROR] django.request: Internal Server Error: /p/test/bugs/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/floppyforms/templates/floppyforms/layouts/table.html", line 1, in template
    {% load floppyforms %}{% block formconfig %}{% formconfig row using "floppyforms/rows/tr.html" %}{% endblock %}
TemplateSyntaxError: Encountered unknown tag 'load'.
2014-01-26 18:32:26,831 [ERROR] django.request: Internal Server Error: /p/test/bugs/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    if settings.TEMPLATE_DEBUG:
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    extensions=(),
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/floppyforms/templates/floppyforms/layouts/table.html", line 1, in template
    {% load floppyforms %}{% block formconfig %}{% formconfig row using "floppyforms/rows/tr.html" %}{% endblock %}
TemplateSyntaxError: Encountered unknown tag 'load'.
2014-01-26 18:32:45,633 [ERROR] django.request: Internal Server Error: /p/test/bugs/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 189, in render
    if settings.TEMPLATE_DEBUG:
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
    extensions=(),
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/floppyforms/templates/floppyforms/layouts/table.html", line 1, in template
    {% load floppyforms %}{% block formconfig %}{% formconfig row using "floppyforms/rows/tr.html" %}{% endblock %}
TemplateSyntaxError: Encountered unknown tag 'load'.
2014-01-26 18:42:58,748 [ERROR] django.request: Internal Server Error: /p/test/bugs/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 195, in render
    return super(Template, self).render(context_dict)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/project_bugs.html", line 2, in top-level template code
    {% from "scrum/includes/macros.html" import toggle_stats_button, bug_table with context %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/base_project.html", line 2, in top-level template code
    {% from "scrum/includes/macros.html" import left_nav %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/base.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/django/scrumbugz/templates/base.html", line 102, in top-level template code
    {% block content %}{% endblock %}
  File "/usr/local/django/scrumbugz/scrum/templates/scrum/project_bugs.html", line 67, in block "content"
    {{ form|safe }}
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/filters.py", line 747, in do_mark_safe
    return Markup(value)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/markupsafe/__init__.py", line 72, in __new__
    return text_type.__new__(cls, base)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/floppyforms/forms.py", line 29, in __str__
    return self._render_as('floppyforms/layouts/default.html')
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/floppyforms/forms.py", line 26, in _render_as
    return self._template_node.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/floppyforms/templatetags/floppyforms.py", line 512, in render
    return super(FormNode, self).render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/floppyforms/templatetags/floppyforms.py", line 476, in render
    output = nodelist.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/floppyforms/templatetags/floppyforms.py", line 636, in render
    output = bound_field.as_widget(widget=widget)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/forms/forms.py", line 475, in as_widget
    return widget.render(name, self.value(), attrs=attrs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/floppyforms/widgets.py", line 98, in render
    context_instance=self.context_instance)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 162, in render_to_string
    t = get_template(template_name)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 263, in do_include
    isolated_context=isolated_context)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 145, in __init__
    t = get_template(template_path)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line 805, in do_for
    sequence = parser.compile_filter(bits[in_index+1])
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 360, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/base.py", line 577, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '()' from 'attrs.items()'
2014-01-26 19:05:35,259 [ERROR] django.request: Internal Server Error: /admin/logout/
Traceback (most recent call last):
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/response.py", line 58, in resolve_template
    return loader.get_template(template)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/template/loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 227, in load_template
    template = env.get_template(template_name)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jingo/__init__.py", line 38, in get_template
    return super(Environment, self).get_template(name, parent, globals)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/loaders.py", line 395, in load
    return loader.load(environment, name, globals)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 554, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/django/scrumbugz/venv/lib/python2.7/site-packages/django/contrib/admin/templates/registration/logged_out.html", line 2, in template
    {% load i18n %}
TemplateSyntaxError: Encountered unknown tag 'load'.
2014-01-27 10:58:46,012 [WARNING] django.request: Not Found: /tasks
